server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri /index.html;
    }

    error_page  404              /index.html;

    # Custom 500 Internal Server Error page
    error_page   500              /500.html;
    location = /500.html {
        root   /usr/share/nginx/html;
    }

    # redirect other server error pages to the static page /50x.html
    error_page   502 503 504      /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}